controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

index:
    path: /
    controller: App\Controller\AccueilController::index

films:
    path: /films
    controller: App\Controller\FilmsController::index

list_film:
    path: /films_list
    controller: App\Controller\FilmsController::films/list